description: error
content:
  application/json:
    schema:
      type: object 
      additionalProperties: true
      required:
        - error
      properties:
        error:
          type: string