openapi: 3.0.0
servers:
  - url: https://<database_url>
    description: Access to your HIDDB databases

info:
  description: |
    Example usage:
    
    ```bash
    curl --location \
         --request GET "https://<database_url>/collection" \
         --header "Accept: application/json" \
    ```

  version: 0.3.0
  title: API documentation
  termsOfService: "https:/hiddb.com/terms"
  license:
    name: Propretary Licence
    url: "https://hiddb.com/licence"
tags:
  - name: Database
    description: Operations on databases
  - name: Instance
    description: Operations on instances
  - name: Collection
    description: Operations on collections
  - name: Index
    description: Operations on indices
  - name: Document
    description: Operations on documents
  - name: Internal
    description: Internal operations

paths:

  ############################## Databases #############################################

  /database:
    $ref: "./database/index.yaml"

  /database/{database_id}:
    $ref: "./database/database_id/index.yaml"

  # ############################## Instances #############################################

  /instance:
    $ref: "./instance/index.yaml"

  /instance/{instance_id}:
    $ref: "./instance/instance_id/index.yaml"

  ############################## Collection #############################################

  /collection:
    $ref: "./collection/index.yaml"

  /collection/{collection_name}:
    $ref: "./collection/collection_name/index.yaml"

  ############################### Index ##################################################

  /collection/{collection_name}/index:
    $ref: "./collection/collection_name/index/index.yaml"

  /collection/{collection_name}/index/{field_name}:
    $ref: "./collection/collection_name/index/field_name/index.yaml"

  # ############################## Document ###############################################

  /collection/{collection_name}/document:
    $ref: "./collection/collection_name/index/document.yaml"

  /collection/{collection_name}/document/search:
    $ref: "./collection/collection_name/index/search.yaml"

  /collection/{collection_name}/document/{document_id}:
    $ref: "./collection/collection_name/document/document_id/index.yaml"

  ############################## Internal #############################################

  /organization/{organization_id}/usage: 
    x-internal: true 
    $ref: "./usage/organization_id/index.yaml"

  /customer/address:
    x-internal: true 
    $ref: "./customer/address.yaml"

  /customer/checkout:
    x-internal: true 
    $ref: "./customer/checkout.yaml"

  /customer/portal:
    x-internal: true 
    $ref: "./customer/portal.yaml"
